// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_create_list
extern "C" SEXP rcpp_create_list();
RcppExport SEXP _crcpp_rcpp_create_list() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_create_list());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP c_ask_for_list();

static const R_CallMethodDef CallEntries[] = {
    {"_crcpp_rcpp_create_list", (DL_FUNC) &_crcpp_rcpp_create_list, 0},
    {"c_ask_for_list",          (DL_FUNC) &c_ask_for_list,          0},
    {NULL, NULL, 0}
};

RcppExport void R_init_crcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
