# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @export
rcpp_create_list <- function() {
    .Call('_crcpp_rcpp_create_list', PACKAGE = 'crcpp')
}

#' @export
rcpp_dont_return_list <- function() {
    invisible(.Call('_crcpp_rcpp_dont_return_list', PACKAGE = 'crcpp'))
}

